### ISSUE TITLE
Thiết kế giao diện trang thanh toán

### ISSUE THREAD

**Issue by SokKimThanh** [SokKimThanh/bachhoaxanh#17]
TxtHoTen:vùng nhập họ tên của khách hàng
TxtSoDt:vùng nhập số điện thoại khách hàng
radGioiTinh: chọn giới tính, chỉ chọn 1 trong 2, luôn chọn trước 1 trong 2
TxtDiaChi: Vùng nhập địa chỉ
radThanhToanchọn 1 trong 2 phương thức thanh toán
btnHoanTat:dùng để thanh toán và qua trang thanh toán thành công hoặc thanh toán thất bại
![image](https://github.com/SokKimThanh/bachhoaxanh/assets/20368186/38246452-a8b8-4542-8875-6bd90b34ef75)

**Comment by giahuy131** [comment]
![Image](https://user-images.githubusercontent.com/103055598/236685211-28ce2dbf-f3cb-4d0b-84c1-6f28492dce04.png)

**Comment by giahuy131** [comment]
TxtHoTen:vùng nhập họ tên của khách hàng
TxtSoDt:vùng nhập số điện thoại khách hàng
radGioiTinh: chọn giới tính, chỉ chọn 1 trong 2, luôn chọn trước 1 trong 2
TxtDiaChi: Vùng nhập địa chỉ
radThanhToanchọn 1 trong 2 phương thức thanh toán
btnHoanTat:dùng để thanh toán và qua trang thanh toán thành công hoặc thanh toán thất bại
