### ISSUE TITLE
Thiết kế giao diện trang thông tin user

### ISSUE THREAD

**Issue by SokKimThanh** [SokKimThanh/bachhoaxanh#23]

**Comment by LeDuyAnhTu** [comment]
![image](https://user-images.githubusercontent.com/132416718/235932071-9e44a926-c012-4729-b3b1-c44b465ebb6a.png)

##Mô tả: 
**txtHo**: Vùng hiển thị họ của khách hàng
**txtTen**: Vùng hiển thị tên của khách hàng
**radGioiTinh**: chọn giới tính, chỉ chọn 1 trong 2, luôn chọn trước 1 trong 2
**txtSDT**: Vùng hiển thị số điện thoại của khách hàng
**txtEmail**: Vùng hiển thị email của khách hàng
**txtMatKhau**: Vùng chứa password của khách
**btnHienThiMatKhau**: Nhấp vào để hiển thị password cho khách hàng nếu họ quên
**btnSua**: Nhấp vào sẽ kích hoạt các vùng txt để người dùng có thể nhập, tạm thời đóng nút btnDangXuat, nút btnSua sẽ là nút đồng ý sửa đổi, nếu các thông được thay đổi phù hợp với quy chuẩn thì sẽ sửa thông tin khách hàng thành thông tin mới nhập. Nút btnThoat sẽ là nút từ chối sửa đổi.
**btnDangXuat**: Dùng để thoát khỏi tài khoản của khách hàng và quay lại frmSearch, lblThongTin ở frmSearch sẽ ẩn đi, **btnDangNhap** và btnDangKy sẽ hiện lên thay chỗ cho lblThongTin
**btnThoat**: Dùng để quay lại frmSearch
